apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-aplicacion
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-aplicacion
  template:
    metadata:
      labels:
        app: mi-aplicacion
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
      - name: mi-aplicacion
        #image: ${{ secrets.ACR_LOGIN_SERVER }}/mycontainer1234:v1.0
        image: mycontainer1234.azurecr.io/mycontainer1234:v1
        ports:
        - containerPort: 8080